# Zephyr feature switches to turn components on and off
# Enable the GPIO driver and subsystem to allow toggling the LED pin (kconfig)
CONFIG_GPIO=y

# Enable C++ support
CONFIG_CPP=y
CONFIG_STD_CPP17=y
